sudo: false
language: python
python:
  - "3.3"
  - "3.4"
  - "3.6"
install: pip install -e ".[dev]"
script: py.test --cov-report=xml --cov-report=html --cov-report term-missing --cov=aws_rotate
after_success:
  - coveralls
